[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
"python" = "3.13"
"aqua:cli/cli" = "2.68.1"
"aqua:helm/helm" = "3.17.2"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.32.3"
"aqua:mikefarah/yq" = "4.45.1"
"aqua:derailed/k9s" = "0.40.10"