[project]
name = "crypto-predictor-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonschema-specifications>=2024.10.1",
    "quixstreams>=3.13.1",
]

[tool.uv.workspace]
members = [
    "services/trades",
]
