---
apiVersion: v1
kind: Service
metadata:
  name: agnhost
  namespace: rwml
spec:
  type: ClusterIP
  selector:
    app: agnhost
  ports:
    - port: 8485
      targetPort: 8080
      protocol: TCP
      name: http
