apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnhost
  namespace: rwml
  labels:
    app: agnhost
spec:
  selector:
    matchLabels:
      app: agnhost
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 3
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agnhost
        prometheus.io/scrape: "false"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: agnhost
          image: ghcr.io/mariusrugan/agnhost:0.1.3-beta.1743798651 # {"$imagepolicy": "rwml:rwml"}
          imagePullPolicy: IfNotPresent
          args:
            - netexec
            - --http-port=8080
            - --udp-port=8080
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: AGNHOST_DEBUG
              value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: {drop: ["ALL"]}
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2000m
              memory: 512Mi
