apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: rwml
  labels:
    app: candles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      containers:
      - name: candles
        image: ghcr.io/real-world-ml/candles:0.1.5-beta.@sha256:fb4a1683f1b18a59a2a62e68d0f221335691f96ed496e732886a5d9bc1fd48b9
        imagePullPolicy: Always # Make sure we use the latest docker images fronm the github container registry, disregarding the caches images that kubernetes might have.
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-c6c8-kafka-bootstrap.strimzi.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "trades"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          value: "60"